# fly.toml app configuration file generated for banterbox-api on 2024-08-19T17:16:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'banterbox-api'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
