name: Deploy on Fly.io

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install fly CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Export fly ENV
        run: export FLYCTL_INSTALL="/home/runner/.fly" && export PATH="$FLYCTL_INSTALL/bin:$PATH"

      - name: Deploy
        run: flyctl deploy
